# Generated by Django 5.2.1 on 2025-06-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('A1', 'Eshitmaydigan'), ('A2', 'Jismoniy nogiron')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', "O'quvchi"), ('teacher', "O'qituvchi")], max_length=20, null=True),
        ),
    ]
