services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-net

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: eedu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Azizbek1410
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot_www:/var/www/certbot
      - certbot_letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - app-net
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_letsencrypt:/etc/letsencrypt
    networks:
      - app-net

volumes:
  certbot_www:
  certbot_letsencrypt:
  postgres_data:

networks:
  app-net:
    driver: bridge
