services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: eedu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Azizbek1410
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    entrypoint: >
      sh -c "sleep 10 && certbot certonly --webroot --webroot-path=/var/www/certbot --email azizbek@example.com --agree-tos --no-eff-email -d edueveryone.uz"

volumes:
  postgres_data:
  certbot-etc:

networks:
  app-network:
